### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by widoz** [hbattat/verifyEmail#11]
Get a Notice regarding the $result variable 

`
if ($getdetails) {
        return array($result, $details);
    } else {
        return $result;
    }
`

`"<br />
<b>Notice</b>:  Undefined variable: result in ... null"
`

**Comment by hbattat** [comment]
It might be because the connection failed

```
$connect = @fsockopen($mx_ip, 25); 
if($connect){
.....
//result is defined here
$result = .....
}
```
`if ($getdetails) { return array($result, $details); } else { return $result; }`

**Comment by widoz** [comment]
I switched the
