### ISSUE TITLE
Undefined variable: details

### ISSUE THREAD

**Issue by VarunAgw** [hbattat/verifyEmail#12]
( ! ) Notice: Undefined variable: details in C:\Server\www\_\verify-email.php on line 30
Call Stack
#	Time	Memory	Function	Location
1	0.0007	353520	{main}( )	...\verify-email.php:0
2	0.0007	353520	verifyEmail( )	...\verify-email.php:73

**Comment by hbattat** [comment]
I defined it at the beginning

**Comment by VarunAgw** [comment]
:+1:
