### ISSUE TITLE
Error on line 22

### ISSUE THREAD

**Issue by borodatych** [hbattat/verifyEmail#13]
Now:
$mx_ip = $mxhosts[array_search(min($mxweight), $mxhosts)];
Need:
$mx_ip = $mxhosts[array_search(min($mxweight), $mxweight)];

1. http://php.net/manual/en/function.min.php
2. http://php.net/manual/en/function.array-search.php

In your code, you seek the minimum value in the array with the weight.
Then on the value of trying to find the key to a completely different array.

I have sent a patch, but you're not treated.

Why?

**Comment by hbattat** [comment]
Your pull request was in a language I did not understand (not in english) but also the code changed completely that I cannot add it to the repo, but I see what the error is now, and I have changed that line to your suggestion. It is true that the code I had did not get the highest priority MX record. This actually does not affect the functionality much, but it is a good point.

Thanks for your help.
