### ISSUE TITLE
Code is not working for yahoo and outlook

### ISSUE THREAD

**Issue by babitabhandari** [hbattat/verifyEmail#15]
Hi Sir , I have used your code an its works for gmail but not work with yahoo and outlook.If i check the incorrect email of yahoo in it its always show it is valid email .please can you give me the solution of verify all email address from yahoo domain.This code is not working for outlook domain,messages are not sent.

**Comment by hbattat** [comment]
I mentioned in the Notes section in README.md that some servers choose to always return "valid" for any email address. Unfortunately this is beyond anybody's control (other than the server target mail server itself) The reason they do that is to prevent spammers (and others) from using "brute force" to generate a list of all email accounts on that server.

So there is no solution for that.

**Comment by babitabhandari** [comment]
Thanx for reply me .

**Comment by hbattat** [comment]
I have added a _potential_ fix for yahoo.com emails
