### ISSUE TITLE
How to add this email in an array ?

### ISSUE THREAD

**Issue by babitabhandari** [hbattat/verifyEmail#17]
I want to check 1000 emails at the same time.I have to check all email addresses in arrayinsterad of check email address  one by one.So i have added one extra email in it and check 2 email addresses at the same time but code is assuming my second email as port no.So please can you tell me the solution of this how we can check 100 emails atthe same time in an array.

 $ve=array();
$ve = new VE\VerifyEmail('dave@gmail.com', 'dave@gmail.com','dave1@hmgamerica.com','dave1@hmgamerica.com');
print_r($ve);
for ($x = 1; $x <= 2; $x++)
{
 
var_dump($ve->verify());

echo '<pre>';print_r($ve->get_debug());
}

**Comment by hbattat** [comment]
The functions expect a string, so you could change the email inside the loop instead, something like:

`$emails = array('dave@gmail.com', 'dave@gmail.com','dave1@hmgamerica.com','dave1@hmgamerica.com'); `

`$ve = new VE\VerifyEmail('<some.placeholder.value@example.com>', '<verifier.email@example.com>');`

Then you do the loop:

```PHP
foreach($emails as $email){
  //change the email to the current item in the loop
  $ve->set_email($email);
  var_dump($ve->verify());
}
```

**Comment by babitabhandari** [comment]
Hi Sir,Thanx for helping me.I have used your code.if i use this line echo '<pre>';print_r($ve->get_debug()); then it show results of that email id which i have mentioned in $ve variable and if i remove this line then it gives me result only boolean false or true.I want that if i use the function get_debug it gives me correct resullt.
 $emails = array('babitabhandari405@gmail.com', 'dave@hmgamerica.com','dave1@hmgamerica.com','dave1@hmgamerica.com');

$ve = new VE\VerifyEmail('dave@hmgamerica.com', 'dave@hmgamerica.com');
foreach($emails as $email){
  //change the email to the current item in the loop
  $ve->set_email($email);
  var_dump($ve->verify());
//echo '<pre>';print_r($ve->get_debug());

}

**Comment by hbattat** [comment]
You could just initiate the class and verify at every loop element. So do everything inside the loop.

**Comment by babitabhandari** [comment]
I have used this get_debug() function inside the foreach loop but still it gives the result like  initialized mail with. The email name is shown which i have mentioned in this line.  
$ve = new VE\VerifyEmail('dave@hmgamerica.com', 'dave@hmgamerica.com'); only Please can you do some changes in my code.

**Comment by hbattat** [comment]
hhahaha, sorry I am not a consultant and do not build scripts for people, this was a small project I thought I would share it with others, but what you are asking for is a bit too much.

From here on, you should try to figure it out on your own :)

Thanks,
