### ISSUE TITLE
All Emails Return as Valid..

### ISSUE THREAD

**Issue by dmorri** [hbattat/verifyEmail#19]
Have you had any luck getting a response back that the email is NOT VALID mailable. If I try emails I know do not exist it still comes back as Email is Valid. My research has show that trying to determine if an email is valid (user and domain...Not just domain) does not work well.

**Comment by dmorri** [comment]
Btw..Gmail seems to be good at allowing you to interrogate email itself (user), but yahoo does not for example or other domains I have tried.

**Comment by dmorri** [comment]
Any research on percentage of domains that you can successfully determine if an email really exists using this method of creating a socket (telnet) into the server and looking for a response)? Thanks!

**Comment by dmorri** [comment]
Here is an example dmorrixy@yahoo.com comes back valid, but it is not and if you try another program like http://www.email-validator.net/ it will tell you its rejected. So something is missing.

**Comment by hbattat** [comment]
From what I have researched there is no way to know from the server if the email is valid or not for servers that choose to return "valid" all the time.

Yahoo seems to be the biggest one out there. http://www.email-validator.net/ might be doing something special to validate.

I have added a special function to validate yahoo.com accounts. It is a hacky way and I'll be testing for sometime before it is definite. (Please see the [last commit I made](https://github.com/hbattat/verifyEmail/commit/c0395fe5187b95a42fbc396df500789199c43734))

**Comment by dmorri** [comment]
Cool. It seems that invalid YAHOO.com emails still come back valid though. :-(

**Comment by hbattat** [comment]
I don't know what you are doing buddy, working fine for me, so if you cannot share more details I cannot help :(
