### ISSUE TITLE
Possible to add a composer.json file describing this package?

### ISSUE THREAD

**Issue by teolaz1990** [hbattat/verifyEmail#22]
Is it possible?
Is it possible also to have it on packagist, with right tagged versions?

**Comment by hbattat** [comment]
Yes, this has been on my plate for a long time. Just did that. Check the latest release :)
it is also added to packagist

**Comment by teolaz1990** [comment]
On .gitignore, please add:
vendor/ (the entire folder)
composer.lock (if not, every time you update a dependence, we can't update it)

**Comment by hbattat** [comment]
I believe vendor is already there.
wasn't sure if I should add composer.lock, but that makes sense. will add it soon.
thanks

**Comment by hbattat** [comment]
Done!

**Comment by teolaz1990** [comment]
Ouch, need to reopen it...
You gitignored composer.phar instead of composer.lock....

**Comment by hbattat** [comment]
The current content of .gitignore is:
```
/tests/
/vendor/
composer.phar
composer.lock
```

composer.phar has been there since the initial commit. It should be there, shouldn't it?
