### ISSUE TITLE
Make constructor parameters optional

### ISSUE THREAD

**Issue by teolaz1990** [hbattat/verifyEmail#23]
Hi,
if you have already set up methods as set_email, set_verifier_email, set_port, you cannot obly the use of constructor with non-optional $email and $verifier_email .
Let's think about it... if i speak of performances, i can reuse the same object to check multiple mail, for example in a foreach loop, using set_email method, but with this kind of constructor the first time i call the new object i am oblied to pass the first email of the array...

```
$emails = array('aaa@bbb.com','ccc@ddd.com','eee@fff.com');
$verifierEmail = 'aaa@aaa.com';

//the wrong way...
$verifyEmail = new VerifyEmail(array_pop($emails),$verifierEmail);
$verifyEmail->verify();
foreach($email as $email){
    $verifyEmail->set_email($email);
    $verifyEmail->verify();
}


//the right way...
$verifyEmail = new VerifyEmail();
$verifyEmail->set_verifier_email($verifierEmail);
foreach($email as $email){
    $verifyEmail->set_email($email);
    $verifyEmail->verify();
}

```

**Comment by hbattat** [comment]
Good point, will add that

**Comment by hbattat** [comment]
Done v1.0.5
