### ISSUE TITLE
Why alert me 'Fatal error: Class 'hbattat\VerifyEmail' not found'?

### ISSUE THREAD

**Issue by DavidFnck** [hbattat/verifyEmail#24]
Fresh man fresh question:

When I run the index.php, the PHP alert me:

```
Fatalerror: Class 'hbattat\VerifyEmail' not found in /Applications/XAMPP/xamppfiles/htdocs/index.php on line 72
```

I have set composer like this:

```
{
    "name": "hbattat/verifyemail",
    "description": "PHP class that can be easily used to verify an email address and make sure it is valid and does exist on the mail server.",
    "type": "library",
    "require": {
        "php": ">= 5"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8.27"
    },
    "license": "Apache",
    "authors": [
        {
            "name": "Sam Battat",
            "email": "hbattat@msn.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "hbattat\\": "./src"
        }
    },
  "require": {
    "hbattat/verifyemail": "<version number>"
  }
}
```

I guess if the `<version number>`I did't insert right, but I can't find the <version number>.

what shoul I do?Thx.

**Comment by hbattat** [comment]
Yes you need the version number, the current version number is 1.0.5
You can find it in GitHub under tags or releases. Or from https://packagist.org/packages/hbattat/verifyemail


Sent using Boxer
On Oct 28, 2016 6:01 PM, DavidFnck <notifications@github.com> wrote:

Fresh man fresh question:

When I run the index.php, the PHP alert me:

Fatalerror: Class 'hbattat\VerifyEmail' not found in /Applications/XAMPP/xamppfiles/htdocs/index.php on line 72


I have set composer like this:

{
    "name": "hbattat/verifyemail",
    "description": "PHP class that can be easily used to verify an email address and make sure it is valid and does exist on the mail server.",
    "type": "library",
    "require": {
        "php": ">= 5"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8.27"
    },
    "license": "Apache",
    "authors": [
        {
            "name": "Sam Battat",
            "email": "hbattat@msn.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "hbattat\\": "./src"
        }
    },
  "require": {
    "hbattat/verifyemail": "<version number>"
  }
}


I guess if the <version number>I did't insert right, but I can't find the .

what shoul I do?Thx.

**Comment by hbattat** [comment]
Also make sure your run composer.phar update after the change

**Comment by DavidFnck** [comment]
Thank you, Succeed!

**Comment by hbattat** [comment]
you are welcome!
