### ISSUE TITLE
If I set a mail server, how often can I verify the email address?

### ISSUE THREAD

**Issue by DavidFnck** [hbattat/verifyEmail#25]
I can verify the email address by your code, but if I use for several times, my IP will be blocked.

so I want to follow your advice to set a mail sever by the linode, I want to know if I set correctly, how often can I verify the list?

will it just like the http://verify-email.org/ or http://www.briteverify.com/ ?so qiuckly.

**Comment by hbattat** [comment]
I believe those services use the same method, but they might have multiple servers (IPs) to distribute the work and not hit the mail servers from the same IP. It all depends on how/when those servers will treat you as a spammer for the number of requests.

Usually email servers expect email requests to be high, but if you, let's say, send a 1000 request in a minute that might be suspicious. It all depends on the server you are requesting.

This code does not guarantee that you don't get black listed.
