### ISSUE TITLE
Yahoo email address verification no longer works

### ISSUE THREAD

**Issue by samlin86** [hbattat/verifyEmail#26]
It looks like Yahoo has removed their JSON check API to check for valid accounts/emails. It now goes to a page not found.

https://github.com/hbattat/verifyEmail/blob/master/src/VerifyEmail.php#L226

**Comment by hbattat** [comment]
I knew it won't work for long. So, now for the hard way!

I just updated the class to verify yahoo emails using the sign up form. It imitates a sign up form submission with the email we want to verify, then parse the response to see if they complained about existing email.

Let's see how long before this breaks too :)

Thanks for reporting. Let me know if you see an issue with the latest update.

**Comment by hbattat** [comment]
This has been fixed in v1.0.6
