### ISSUE TITLE
Yahoo email working wrong

### ISSUE THREAD

**Issue by kjmtrue** [hbattat/verifyEmail#30]
I try verify email: alexwillis2011@yahoo.com

It return email valid.

But when i send email to this address, google response

> Delivery to the following recipient failed permanently: 
>      alexwillis2011@yahoo.com
> Technical details of permanent failure:
> Google tried to deliver your message, but it was rejected by the server for the recipient domain yahoo.com by mta5.am0.yahoodns.net. [98.136.217.202].
> 
> The error that the other server returned was:
> 554 delivery error: dd This user doesn't have a yahoo.com account (alexwillis2011@yahoo.com) [-5] - mta1325.mail.gq1.yahoo.com

**Comment by hbattat** [comment]
Yahoo accounts can be used for many other products than just Yahoo mail. That account exists, but may not have a mailbox. See this [article](http://money.cnn.com/2016/09/23/technology/yahoo-account-hack/) for some of the services that people create yahoo account for.
