### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Soomrojb** [hbattat/verifyEmail#31]
It always shows "[18] => Not found! Email is invalid." and when I put gmail email, it shows additional errors:

Notice: fputs(): send of 37 bytes failed with errno=32 Broken pipe in /home/pi/languages/git/php/emails/verifyEmail/src/VerifyEmail.php on line 145

Notice: fputs(): send of 4 bytes failed with errno=32 Broken pipe in /home/pi/languages/git/php/emails/verifyEmail/src/VerifyEmail.php on line 151
bool(false)

**Comment by apoguy** [comment]
It does work, must be something with your installation. Did you use composer?

**Comment by hbattat** [comment]
I thought I had replied to this. Thanks @apoguy for helping.
The notice you get is usually due a closed socket. This can be caused by many things, one can be that your serve is blocked?
Also, make sure the installation is correct and that you have the latest version.

**Comment by nepman600** [comment]
[8] => Connection to server failed.
