### ISSUE TITLE
Incorrect TRUE return

### ISSUE THREAD

**Issue by 2ndGAB** [hbattat/verifyEmail#33]
Hi, 
I checked your code and I get, I think , an incorrect behavior:

     debug($ve);

    object(hbattat\VerifyEmail) {
        email => 'doesnot.exists@nodomain.com'
        verifier_email => 'noreply@myweb.com'
        port => (int) 25
        [private] mx => null
        [private] connect => null
        [private] errors => null
        [private] debug => [
            (int) 0 => 'Initialized with Email: doesnot.exists@nodomain.com, Verifier Email: noreply@myweb.com, Port: 25',
            (int) 1 => 'Email was set to doesnot.exists@nodomain.com',
            (int) 2 => 'Verifier Email was set to noreply@myweb.com',
            (int) 3 => 'Port was set to 25'
        ]
        [private] debug_raw => []
        [private] _yahoo_signup_page_url => 'https://login.yahoo.com/account/create?specId=yidReg&lang=en-US&src=&done=https%3A%2F%2Fwww.yahoo.com&display=login'
        [private] _yahoo_signup_ajax_url => 'https://login.yahoo.com/account/module/create?validateField=yid'
        [private] yahoo_signup_page_content => null
        [private] yahoo_signup_page_headers => null
    }

    debug($ve->verify());

    true

Why true??

**Comment by apoguy** [comment]
nodomain.com is a catch all domain. that's why you get true as a response. Server accepts email to any address you mail within that domain.
