### ISSUE TITLE
As of may 8th, 2017, authentication with yahoo does not work. I have fixed it.

### ISSUE THREAD

**Issue by jpmaciasg** [hbattat/verifyEmail#34]
Hello. Authentication with yahoo has stopped working. I have fixed it, let me know how can I send you the code to review.

Greetings.

**Comment by jpmaciasg** [comment]
Sorry, forgot NDA

**Comment by fzlilani** [comment]
@jpmaciasg. The yahoo authentication fix that you did earlier, Can you help me? the script does not authenticate yahoo email ids anymore.

**Comment by hbattat** [comment]
I will have some time this week to update the script and fix the problems.
