### ISSUE TITLE
Yahoo validation is not working now

### ISSUE THREAD

**Issue by leopathu** [hbattat/verifyEmail#36]
Hi,

Recently, the yahoo validation is not working but it was working before, could you check it ?

**Comment by ikay007** [comment]
doesn't work for gmail also though it used too.

**Comment by v1ra1** [comment]
`    private function get_yahoo_cookies(){
      $this->debug[] = 'Attempting to get the cookies from the sign up page...';
      if($this->yahoo_signup_page_content !== false){
        $this->debug[] = 'Extracting cookies from headers...';
        $cookies = array();
        foreach ($this->yahoo_signup_page_headers as $hdr) {
          if (preg_match('/^(Set-Cookie|set-cookie):\s*(.*?;).*?$/', $hdr, $matches)) {
            $cookies[] = $matches[2];
          }
        }

        if(count($cookies) > 0){
          $this->debug[] = 'Cookies found: '.implode(' ', $cookies);
          return $cookies;
        }
        else{
          $this->debug[] = 'Could not find any cookies.';
        }
      }`

**Comment by v1ra1** [comment]
if (preg_match('/^(Set-Cookie|set-cookie):\s*(.*?;).*?$/', $hdr, $matches)) {
            $cookies[] = $matches[2];

Replace line 278 and 279 with this.

**Comment by fzlilani** [comment]
@v1ra1  It still doesn't work! can you help?

**Comment by hbattat** [comment]
Fixed. see v1.0.8
