### ISSUE TITLE
Maximum number of verification per SMTP server per day

### ISSUE THREAD

**Issue by postmeee** [hbattat/verifyEmail#41]
Hello,
Can I ask the maximum number of email verification per SMTP server per day without blocking the server. I am asking your experience. 
regards

**Comment by hbattat** [comment]
It depends. but if I have to guess that number is probably high. The main thing is you have to have your mail server configured correctly to avoid being detected as spam and blocked. See http://curlybrac.es/2016/07/27/how-to-configure-a-mail-server/
