### ISSUE TITLE
Undefined index: IfExistsResult in VerifyEmail.php on line 285

### ISSUE THREAD

**Issue by allangdy** [hbattat/verifyEmail#51]
Everything else is working except the hotmail function

@hbattat Thank's a lot for this script

**Comment by ganeshthandapani** [comment]
Hi, @hbattat really nice work. Thanks for the Idea. Hotmail function is not working @allangdy  @hbattat do you have any idea on this.

**Comment by allangdy** [comment]
@geneshthandapani just remove the validation from Hotmail and let it verify the normal way, Hotmail actually accepts this kind of verification now

**Comment by ganeshthandapani** [comment]
Ok, @allangdy thanks for the reply. If I use the normal method will my IP get blocked? Since 1 year back I use this normal telnet process to verify Hotmail domains that time my IP got blocked. Is the technique to avoid blocking.

**Comment by allangdy** [comment]
Multiple machines with load balancing, correct set of DKIM, SPF, make your
server looks the most legit you can, I save all the emails that was already
checked in the last 24 hours on a database and I don't check then again if
they are in the DB, I made several changes to the original code, some mail
servers warns you about too much checks be aware of this kind of response
and make this specific server don't make another request for one week

Em ter, 11 de jun de 2019 07:47, ganeshthandapani <notifications@github.com>
escreveu:

**Comment by hbattat** [comment]
@ganeshthandapani if your mail server is configured correctly. I had a blog post about how to set it up and check. https://curlybrac.es/2016/07/27/how-to-configure-a-mail-server/

On the other hand, using the signup workaround for Hotmail/yahoo/Mail and others was just to solve the issue of catch-all servers. I have not checked Hotmail recently, so I am not aware if they return correct values for valid/invalid emails.
